spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-34-231-63-30.compute-1.amazonaws.com/d7sd84cjjjbc3i
  username: rrrwuwggowjifb
  password: c3b0398a318451084cf5089f2f12b8938ec3c0b0ebcbb2c0fe469c8b21a5f556
  platform: postgres
  driver-class-name: org.postgresql.Driver

#JWT 설정
jwt:
  secret-key: primarchan.sns-application-2022.secret_key
  # 30 Days
  token.expired-time-ms: 2592000000

# Redis 설정
spring.redis.url: redis://:p113bfabb593c4e5270525b17d5c3f13102b02aa7dcef2523b55d0ad89be743f5@ec2-54-204-184-129.compute-1.amazonaws.com:11889

# Kafka 설정
spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="v6ypjj8e" password="LA3qEb9Ix-XIk7qKQRACc68pJF5YfK5d";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: v6ypjj8e-alarm



